import React from "react";
import { Container } from "../Container";
import { TitleWithIcon } from "../Title";
import Image from "next/image";
import { useRouter } from "next/router";
import { ButtonLink } from "../Button";
import { HeartIcon } from "@heroicons/react/solid";
const data = [
  {
    id: 1,
    slug: "/pro-1",
    image: "/images/news-1.jpg",
    beneficiary: 25,
    text: {
      "ar-SA": {
        title: "برنامج ذبح الاضاحي وتزيع لحوم",
        description: `
                هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.
               .
                `,
      },
      "en-US": {
        title: "Program for the harvest and the sale of hay",
        description: `
            This is a dummy text that can be used to replace the text in the same space, which has been generated by the Arabic text generator, where you can generate a lot of other texts by adding to the number of characters that the application generates.
            `,
      },
    },
  },
  {
    id: 2,
    slug: "/pro-1",
    image: "/images/news-2.jpg",
    beneficiary: 25,
    text: {
      "ar-SA": {
        title: "برنامج ذبح الاضاحي وتزيع لحوم",
        description: `
                هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.
                `,
      },
      "en-US": {
        title: "Program for the harvest and the sale of hay",
        description: `
            This is a dummy text that can be used to replace the text in the same space, which has been generated by the Arabic text generator, where you can generate a lot of other texts by adding to the number of characters that the application generates.
            `,
      },
    },
  },
  {
    id: 3,
    slug: "/pro-1",
    image: "/images/news-2.jpg",
    beneficiary: 25,
    text: {
      "ar-SA": {
        title: "برنامج ذبح الاضاحي وتزيع لحوم",
        description: `
                هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.
                `,
      },
      "en-US": {
        title: "Program for the harvest and the sale of hay",
        description: `
            This is a dummy text that can be used to replace the text in the same space, which has been generated by the Arabic text generator, where you can generate a lot of other texts by adding to the number of characters that the application generates.
            `,
      },
    },
  },
];

const LatestProjects = () => {
  const prevRef = React.useRef(null);
  const nextRef = React.useRef(null);
  return (
    <section className="py-14">
      <Container>
        <TitleWithIcon title="أحدث المشاريع" />
        <div className=" grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 mt-10">
          {data.map((project) => (
            <ProjectCard {...project} />
          ))}
        </div>
      </Container>
    </section>
  );
};

export default LatestProjects;

const ProjectCard = ({ image, text, slug, beneficiary, id }) => {
  const { locale } = useRouter();
  const { title, description } = text[locale];
  return (
    <div className=" border border-lightPurple ">
      <div className="relative h-[250px] w-full ">
        <Image src={image} layout="fill" objectFit="cover" />
      </div>
      <div className="p-4">
        <h2 className="text-primaryPurple font-medium mb-4">
          {title} {id}
        </h2>
        <p>{description}</p>
        <div className="flex md:flex-row flex-col gap-4 mt-5 justify-center">
          <ButtonLink href="/">تبرع الأن</ButtonLink>
          <ButtonLink href="/" variant="outline">
            <div className="flex gap-2   ">
              <HeartIcon className="w-5 h-5 " />
              {beneficiary}
              <p>مستفيد</p>
            </div>
          </ButtonLink>
        </div>
      </div>
    </div>
  );
};
